### ISSUE TITLE
Auto reverse seeding, without needing table names

### ISSUE THREAD

**Issue by liaogz82** [orangehill/iseed#34]
Hi guys,

Is there a way to do laravel iseed reverse seeding without using table names? just the database parameters will do

**Comment by rhyudek1** [comment]
would be nice to have a command like 
``` bash
php artisan iseed * [--force]
```
I really appreciate it ...

**Comment by tihomiro** [comment]
That's a good suggestion, though Laravel doesn't have a method to list all DB tables so we'd be stretching a bit further out than we'd feel comfortable to. We'll discuss the idea though. Thanks!

**Comment by vpakg** [comment]
@tihomiro would you not be able to do something like `$tables = DB::select('SHOW TABLES');` and loop them?

**Comment by tihomiro** [comment]
@vpakg That'd cover MYSQL only. However, Laravel supports MySQL, Postgres, SQLite and SQL Server, so this won't work. It'd be nice if Laravel had listAllTables method that deals with all systems. That'd make it easy for us to add this feature. Otherwise it's a bit more of work, and aside from that - it doesn't feel natural for iSeed to solve this problem.

It's doable, but for now devs can loop through tables on their own, depending on a databases system they use.

**Comment by vpakg** [comment]
That's true. I didn't take into consideration the fact that it supports multiple database formats. Oh well.
