### ISSUE TITLE
Compact format

### ISSUE THREAD

**Issue by barbushin** [orangehill/iseed#60]
Is it possible to generate seeder data in more compact format?

For example now, table with 20k rows(US cities coordinates) size in iseed format is 5.7Mb, but in SQL dump format it takes just 1Mb, gzipped SQL dump - just 0.35Mb.

**Comment by tihomiro** [comment]
The goal was not to create a small file, but a utility that would transfer the data between databases using laravel framework as a medium. If you wish you can script the DB export/import so that you add compression on output and decompression on input file if this is something that's a problem you need to solve.
