### ISSUE TITLE
Suggestion: Use PHP_EOL instead of hard-coded Windows CRLF

### ISSUE THREAD

**Issue by archfrog** [orangehill/iseed#70]
Hi,

I am very happy about iseed, it saves me tons of work.  But I use it on Linux and therefore tend to get weird Windos CRLF characters in my source code (which I occasionally edit manually).

Is there any chance that you can change this line:

```
private $newLineCharacter = "\r\n";
```

Into:

```
private $newLineCharacter = PHP_EOL;
```

Cheers,
Mikael

**Comment by tihomiro** [comment]
Although this makes perfect sense, I've hit the brick wall while trying to pass the phpunit tests. That's because the stubs files used for certain assertions (e.g. https://github.com/orangehill/iseed/blob/master/tests/Stubs/seed_5.stub) were created on Windows, I'm running Mac, and Travis CI is on Linux.

@archfrog  any ideas on how to make this work?

**Comment by archfrog** [comment]
I was thinking you could perhaps change the calls to `file_get_contents` in [lseedTest.php, testPopulateStubs()](https://github.com/orangehill/iseed/blob/master/tests/IseedTest.php#L22) with a custom function that converts the external Windows CRLF format into PHP_EOL format?

Unfortunately, I'm not familiar with phpunit and Mockery, so I don't know what EOL format they use internally.  I don't know if they somehow, somewhere compare the actual contents of the files.

**Comment by tihomiro** [comment]
Thanks @archfrog your advice inspired me to land with a custom function

```
    public function readStubFile($file)
    {
        $buffer = file($file, FILE_IGNORE_NEW_LINES);
        return implode(PHP_EOL, $buffer);
    }
```

... which works really well!

Changes applied with https://github.com/orangehill/iseed/pull/79
