### ISSUE TITLE
Postgres Sequence Counter Problem

### ISSUE THREAD

**Issue by msamdan** [orangehill/iseed#91]
Sequence counter is not incrementing.
Laravel 5.4, Postgresql 9.5.

**Comment by tihomiro** [comment]
I can't be 100% sure under what circumstances you're experiencing this issue, but in general, iSeed doesn't manage auto increments in any way. If you're exporting all table columns you should have your ids set the way they were on exporting. If you exclude the id column, you must set your table structure so that ids are generated automatically.

If I misunderstood your problem, please provide more info and I'll reopen this issue, otherwise, I'm closing it.

**Comment by henryavila** [comment]
I'm using this packages for the fist time, and I having the exactly same problem.
I`m migrating the DB from MySql to Postgres.
I created all seeds in mysql production environment,
run the migration in the new environment and run migrate to replicate the same DB structure.
And then, run the seed.

It works great, all data are migrated successfully, but anything I try to insert in DB, I always get a foreign key error alerting that the id 1 already exists.

Any ideas how to bypass this?

**Comment by HenoTaMyJIb** [comment]
If somebody else is having this problem, here is my solution. I have separate seeder class for all sequences.
```
$maxId = DB::table('users')->max('id');
 DB::update('ALTER SEQUENCE users_id_seq RESTART WITH '.($maxId + 1).';');
```
